version: '3.9'

services:
  app:
    build: .
    container_name: nestjs-user-service
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start:prod"

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  mysqldata: